sudo: required
services:
 - docker
language: node_js
matrix:
  include:
    - node_js: '10'
    - node_js: '12'
os:
 - linux
install: yarn install --pure-lockfile
script:
  - yarn run lint
  - yarn run test-ci
cache:
  yarn: true
  directories:
    - node_modules
